email_addr: email@example.com
email_server: mail.example.com
email_pass: pass
imap_port: 143
fetch_mail_every: 600  # in sec

database_url: postgresql://user:secret@localhost/db_name

service_url: mail2rss.example.com
server_port: 8998

admin_pass: "my-very-password"  # used to add aliases
