email_addr: email@example.com
email_server: mail.example.com
email_pass: pass
imap_port: 143

database_url: postgresql://user:secret@localhost/db_name

service_url: mail2rss.example.com
server_port: 8998
